server:
  port: 8080

spring:
  # ▼▼▼ SQS 운영 환경 설정 (진짜 AWS 연결) ▼▼▼
  cloud:
    aws:
      region:
        static: ap-northeast-2 # 서울 리전 명시
      # 🚨 보안을 위해 credentials(access/secret key)는 절대 적지 않습니다! (EC2 IAM Role 사용)
      # 🚨 endpoint도 적지 않습니다! (알아서 진짜 AWS SQS 주소로 찾아갑니다)

  data:
    redis:
      host: ${REDIS_HOST} # 배포 서버의 Redis 주소 (AWS ElastiCache 등)
      port: 6379

  datasource:
    # AWS RDS 주소 예시
    url: jdbc:mysql://${RDS_HOSTNAME}:3306/catchme?useSSL=false&serverTimezone=Asia/Seoul&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate # 🚨 운영에선 절대 create/update 금지! (validate: 스키마 맞는지 확인만 함)
    show-sql: false      # 🚨 운영에선 로그 끄기 (성능 저하 방지)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect