spring:
  application:
    name: catchme
  profiles:
    active: local # 👈 기본 실행 모드를 'local'로 설정 (중요!)

# [공통] JWT, AWS, Kakao 등 환경과 무관한 키값들
jwt:
  issuer: ${JWT_ISSUER}
  secret-key: ${JWT_SECRET_KEY}

aws:
  s3:
    bucket: catchme-raw-data-2025-jiwon
  region: ap-northeast-2

kakao:
  rest-api-key: ${KAKAO_REST_API_KEY}

ai:
  fastapi:
    url: ${FASTAPI_URL}

# [공통] Resilience4j (서킷 브레이커) 설정은 보통 같이 가져감
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
    instances:
      kakaoApi:
        baseConfig: default
      aiPrediction:
        baseConfig: default
        waitDurationInOpenState: 20s

  bulkhead:
    instances:
      aiPrediction:
        maxConcurrentCalls: 10
        maxWaitDuration: 0ms
      kakaoApi:
        maxConcurrentCalls: 20
        maxWaitDuration: 200ms