spring:
  application:
    name: catchme

  datasource:
    url: jdbc:h2:mem:${H2_DB_NAME}
    driver-class-name: org.h2.Driver
    username: ${H2_USERNAME}
    password: ${H2_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update   # 초기 개발용
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: ${SERVER_PORT}

  jwt:
    issuer: ${JWT_ISSUER}
    secret-key: ${JWT_SECRET_KEY}

aws:
  s3:
    bucket: catchme-raw-data-2025-jiwon
  region: ap-northeast-2

kakao:
  rest-api-key: ${KAKAO_REST_API_KEY}

ai:
  fastapi:
    url: ${FASTAPI_URL}

# Resilience4j 서킷 브레이커 설정
resilience4j:
  circuitbreaker: # 1. 서킷 브레이커 (장애 감지 및 차단)
    configs:
      default: # 기본 설정 템플릿
        registerHealthIndicator: true  # Actuator 상태 체크에 포함
        slidingWindowType: COUNT_BASED # 횟수 기반으로 통계 집계
        slidingWindowSize: 10          # 최근 10번의 요청을 기록
        minimumNumberOfCalls: 5        # 최소 5번은 호출해야 통계 계산 시작
        failureRateThreshold: 50       # 실패율이 50% 넘으면 서킷 오픈 (차단)
        waitDurationInOpenState: 10s   # 10초 동안은 차단 상태 유지 (API 호출 안 함)
        permittedNumberOfCallsInHalfOpenState: 3 # 10초 후, 3번만 살짝 찔러보기 (테스트)

    instances:
      kakaoApi: # 우리가 사용할 서킷 브레이커 이름
        baseConfig: default # 위 설정을 상속받음
      aiPrediction: # [NEW] AI 서버용
        baseConfig: default
        waitDurationInOpenState: 20s # AI 서버는 복구에 시간이 더 걸릴 수 있으므로 20초 대기
    # 2. 벌크헤드 (동시 요청 제한 - AI 서버용 필수 설정!)
    bulkhead:
      instances:
        aiPrediction:
          maxConcurrentCalls: 10 # 🔥 동시에 최대 5명까지만 AI 분석 요청 가능 (스레드 보호)
          maxWaitDuration: 0ms  # 대기 줄(Queue) 없이 즉시 거절 (Fail Fast)